$(function(){	
	var cities = [ 
		"Abilene, TX",
		"Akron, OH",
		"Alameda, CA",
		"Albany, NY",
		"Albany, GA",
		"Albany, OR",
		"Albuquerque, NM",
		"Alexandria, VA",
		"Alexandria, LA",
		"Alhambra, CA",
		"Aliso Viejo, CA",
		"Allen, TX",
		"Allentown, PA",
		"Aloha, OR",
		"Alpharetta, GA",
		"Altadena, CA",
		"Altoona, PA",
		"Amarillo, TX",
		"Ames, IA",
		"Anaheim, CA",
		"Anchorage, AK",
		"Anderson, IN",
		"Ankeny, IA",
		"Annandale, VA",
		"Ann Arbor, MI",
		"Antioch, CA",
		"Appleton, WI",
		"Apple Valley, CA",
		"Apple Valley, MN",
		"Arcadia, CA",
		"Arden-Arcade, CA",
		"Arlington, TX",
		"Arlington, VA",
		"Arlington, MA",
		"Arlington Heights, IL",
		"Arvada, CO",
		"Asheville, NC",
		"Aspen Hill, MD",
		"Athens-Clarke, GA",
		"Atlanta, GA",
		"Attleboro, MA",
		"Auburn, AL",
		"Auburn, WA",
		"Augusta-Richmond, GA",
		"Aurora, CO",
		"Aurora, IL",
		"Austin, TX",
		"Avondale, AZ",
		"Azusa, CA",
		"Bakersfield, CA",
		"Baldwin Park, CA",
		"Baltimore, MD",
		"Barnstable Town, MA",
		"Bartlett, TN",
		"Bartlett, IL",
		"Baton Rouge, LA",
		"Battle Creek, MI",
		"Bayonne, NJ",
		"Baytown, TX",
		"Beaumont, TX",
		"Beaverton, OR",
		"Bedford, TX",
		"Bel Air North, MD",
		"Bel Air South, MD",
		"Belleville, IL",
		"Bellevue, WA",
		"Bellevue, NE",
		"Bellflower, CA",
		"Bell Gardens, CA",
		"Bellingham, WA",
		"Bend, OR",
		"Berkeley, CA",
		"Berwyn, IL",
		"Bethesda, MD",
		"Bethlehem, PA",
		"Billerica, MA",
		"Billings, Montana",
		"Biloxi, MS",
		"Binghamton, NY",
		"Birmingham, AL",
		"Bismarck, ND",
		"Blacksburg, VA",
		"Blaine, MN",
		"Bloomfield, NJ",
		"Bloomfield Township, MI",
		"Bloomington, MN",
		"Bloomington, IL",
		"Bloomington, IN",
		"Blue Springs, MO",
		"Boca Raton, FL",
		"Boise City, ID",
		"Bolingbrook, IL",
		"Bonita Springs, FL",
		"Bossier City, LA",
		"Boston, MA",
		"Boulder, CO",
		"Bountiful, UT",
		"Bowie, MD",
		"Bowling Green, KY",
		"Boynton Beach, FL",
		"Bozeman, Montana",
		"Bradenton, FL",
		"Brandon, FL",
		"Brentwood, NY",
		"Brentwood, CA",
		"Brick, NJ",
		"Bridgeport, CT",
		"Bristol, CT",
		"Brockton, MA",
		"Broken Arrow, OK",
		"Brookline, MA",
		"Brooklyn Park, MN",
		"Broomfield, CO",
		"Brownsville, TX",
		"Bryan, TX",
		"Buckeye, AZ",
		"Buena Park, CA",
		"Buffalo, NY",
		"Buffalo Grove, IL",
		"Bullhead City, AZ",
		"Burbank, CA",
		"Burke, VA",
		"Burlington, NC",
		"Burnsville, MN",
		"Caldwell, ID",
		"Calexico, CA",
		"Camarillo, CA",
		"Cambridge, MA",
		"Camden, NJ",
		"Canton, MI",
		"Canton, OH",
		"Cape Coral, FL",
		"Carlsbad, CA",
		"Carmel, IN",
		"Carmichael, CA",
		"Carol City, FL",
		"Carol Stream, IL",
		"Carrollton, TX",
		"Carson, CA",
		"Carson City, NV",
		"Cary, NC",
		"Casa Grande, AZ",
		"Casas Adobes, AZ",
		"Casper, Wyoming",
		"Castle Rock, CO",
		"Castro Valley, CA",
		"Catalina Foothills, AZ",
		"Cathedral City, CA",
		"Catonsville, MD",
		"Cedar Hill, TX",
		"Cedar Park, TX",
		"Cedar Rapids, IA",
		"Centennial, CO",
		"Centreville, VA",
		"Ceres, CA",
		"Cerritos, CA",
		"Champaign, IL",
		"Chandler, AZ",
		"Chantilly, VA",
		"Chapel Hill, NC",
		"Charleston, SC",
		"Charleston, West VA",
		"Charlotte, NC",
		"Charlottesville, VA",
		"Chattanooga, TN",
		"Cheektowaga, NY",
		"Chelsea, MA",
		"Cherry Hill, NJ",
		"Chesapeake, VA",
		"Chesterfield, MO",
		"Cheyenne, Wyoming",
		"Chicago, IL",
		"Chico, CA",
		"Chicopee, MA",
		"Chino, CA",
		"Chino Hills, CA",
		"Chula Vista, CA",
		"Cicero, IL",
		"Cincinnati, OH",
		"Citrus Heights, CA",
		"Clarksville, TN",
		"Clearwater, FL",
		"Cleveland, OH",
		"Cleveland, TN",
		"Cleveland Heights, OH",
		"Clifton, NJ",
		"Clovis, CA",
		"Coachella, CA",
		"Coconut Creek, FL",
		"Coeur d'Alene, ID",
		"College Station, TX",
		"CO Springs, CO",
		"Colton, CA",
		"Columbia, SC",
		"Columbia, MO",
		"Columbia, MD",
		"Columbus, OH",
		"Columbus, GA",
		"Commerce City, CO",
		"Compton, CA",
		"Concord, CA",
		"Concord, NC",
		"Concord, NH",
		"Conroe, TX",
		"Conway, AR",
		"Coon Rapids, MN",
		"Coral Gables, FL",
		"Coral Springs, FL",
		"Corona, CA",
		"Corpus Christi, TX",
		"Corvallis, OR",
		"Costa Mesa, CA",
		"Council Bluffs, IA",
		"Country Club, FL",
		"Covina, CA",
		"Covington, KY",
		"Cranston, RI",
		"Crystal Lake, IL",
		"Cupertino, CA",
		"Cuyahoga Falls, OH",
		"Cypress, CA",
		"Dale City, VA",
		"Dallas, TX",
		"Daly City, CA",
		"Danbury, CT",
		"Danville, VA",
		"Danville, CA",
		"Davenport, IA",
		"Davie, FL",
		"Davis, CA",
		"Dayton, OH",
		"Daytona Beach, FL",
		"Dearborn, MI",
		"Dearborn Heights, MI",
		"Decatur, IL",
		"Decatur, AL",
		"Deerfield Beach, FL",
		"DeKalb, IL",
		"Delano, CA",
		"Delray Beach, FL",
		"Deltona, FL",
		"Denton, TX",
		"Denver, CO",
		"Des Moines, IA",
		"DeSoto, TX",
		"Des Plaines, IL",
		"Detroit, MI",
		"Diamond Bar, CA",
		"Dothan, AL",
		"Downers Grove, IL",
		"Downey, CA",
		"Draper, UT",
		"Drexel Heights, AZ",
		"Dublin, CA",
		"Dubuque, IA",
		"Duluth, MN",
		"Dundalk, MD",
		"Durham, NC",
		"Eagan, MN",
		"East Brunswick, NJ",
		"East Hartford, CT",
		"East Lake, FL",
		"East Lansing, MI",
		"East Los Angeles, CA",
		"East Orange, NJ",
		"East Point, GA",
		"East Providence, RI",
		"Eau Claire, WI",
		"Eden Prairie, MN",
		"Edina, MN",
		"Edinburg, TX",
		"Edison, NJ",
		"Edmond, OK",
		"Edmonds, WA",
		"Egypt Lake-Leto, FL",
		"El Cajon, CA",
		"El Centro, CA",
		"Eldersburg, MD",
		"Elgin, IL",
		"Elizabeth, NJ",
		"Elk Grove, CA",
		"Elkhart, IN",
		"Ellicott City, MD",
		"Elmhurst, IL",
		"El Monte, CA",
		"El Paso, TX",
		"Elyria, OH",
		"Encinitas, CA",
		"Enid, OK",
		"Erie, PA",
		"Escondido, CA",
		"Euclid, OH",
		"Eugene, OR",
		"Euless, TX",
		"Evanston, IL",
		"Evansville, IN",
		"Everett, WA",
		"Fairfield, CA",
		"Fairfield, CT",
		"Fairfield, OH",
		"Fall River, MA",
		"Fargo, ND",
		"Farmington, NM",
		"Farmington Hills, MI",
		"Fayetteville, NC",
		"Fayetteville, AR",
		"Federal Way, WA",
		"Fishers, IN",
		"Flagstaff, AZ",
		"Flint, MI",
		"Florence-Graham, CA",
		"Florissant, MO",
		"Flower Mound, TX",
		"Folsom, CA",
		"Fond du Lac, WI",
		"Fontana, CA",
		"Fort Collins, CO",
		"Fort Lauderdale, FL",
		"Fort Myers, FL",
		"Fort Pierce, FL",
		"Fort Smith, AR",
		"Fortuna Foothills, AZ",
		"Fort Wayne, IN",
		"Fort Worth, TX",
		"Fountainbleau, FL",
		"Fountain Valley, CA",
		"Framingham, MA",
		"Franconia, VA",
		"Franklin, TN",
		"Frederick, MD",
		"Freeport, NY",
		"Fremont, CA",
		"Fresno, CA",
		"Frisco, TX",
		"Fullerton, CA",
		"Gainesville, FL",
		"Gaithersburg, MD",
		"Galveston, TX",
		"Gardena, CA",
		"Garden Grove, CA",
		"Garland, TX",
		"Gary, IN",
		"Gastonia, NC",
		"Georgetown, TX",
		"Germantown, MD",
		"Gilbert, AZ",
		"Gilroy, CA",
		"Glendale, AZ",
		"Glendale, CA",
		"Glendora, CA",
		"Glenview, IL",
		"Goodyear, AZ",
		"Goose Creek, SC",
		"Grand Forks, ND",
		"Grand Island, NE",
		"Grand Junction, CO",
		"Grand Prairie, TX",
		"Grand Rapids, MI",
		"Grapevine, TX",
		"Greater Carrollwood, FL",
		"Great Falls, MT",
		"Greeley, CO",
		"Green Bay, WI",
		"Greensboro, NC",
		"Greenville, NC",
		"Greenville, SC",
		"Greenwich, CT",
		"Greenwood, IN",
		"Gresham, OR",
		"Gulfport, MI",
		"Hacienda Heights, CA",
		"Hackensack, NJ",
		"Haltom City, TX",
		"Hamden, CT",
		"Hamilton, NJ",
		"Hamilton, OH",
		"Hammond, IN",
		"Hampton, VA",
		"Hanford, CA",
		"Harlingen, TX",
		"Harrisburg, PA",
		"Harrisonburg, VA",
		"Hartford, CT",
		"Hattiesburg, MI",
		"Haverhill, MA",
		"Hawthorne, CA",
		"Hayward, CA",
		"Hemet, CA",
		"Hempstead, NY",
		"Henderson, NV",
		"Hendersonville, TN",
		"Hesperia, CA",
		"Hialeah, FL",
		"Hickory, NC",
		"Hicksville, NY",
		"Highland, CA",
		"Highlands Ranch, CO",
		"High Point, NC",
		"Hillsboro, OR",
		"Hilo, Hawaii",
		"Hoboken, NJ",
		"Hoffman Estates, IL",
		"Hollywood, FL",
		"Homestead, FL",
		"Honolulu, Hawaii",
		"Hoover, AL",
		"Houston, TX",
		"Huntersville, NC",
		"Huntington, West VA",
		"Huntington Beach, CA",
		"Huntington Park, CA",
		"Huntsville, AL",
		"Hutchinson, KS",
		"Idaho Falls, ID",
		"Independence, MO",
		"INpolis, IN",
		"Indio, CA",
		"Inglewood, CA",
		"IA City, IA",
		"Irondequoit, NY",
		"Irvine, CA",
		"Irving, TX",
		"Irvington, NJ",
		"Jackson, MI",
		"Jackson, TN",
		"Jacksonville, FL",
		"Jacksonville, NC",
		"Janesville, WI",
		"Jefferson City, MO",
		"Jersey City, NJ",
		"Johns Creek, GA",
		"Johnson City, TN",
		"Joliet, IL",
		"Jonesboro, AR",
		"Joplin, MO",
		"Jupiter, FL",
		"Kalamazoo, MI",
		"Kannapolis, NC",
		"Kansas City, MO",
		"Kansas City, KS",
		"Keller, TX",
		"Kendale Lakes, FL",
		"Kendall, FL",
		"Kendall West, FL",
		"Kenner, LA",
		"Kennewick, WA",
		"Kenosha, WI",
		"Kent, WA",
		"Kentwood, MI",
		"Kettering, OH",
		"Killeen, TX",
		"Kingsport, TN",
		"Kirkland, WA",
		"Kissimmee, FL",
		"Knoxville, TN",
		"Kokomo, IN",
		"Lacey, WA",
		"La Crosse, WI",
		"Lafayette, LA",
		"Lafayette, IN",
		"Laguna, CA",
		"Laguna Niguel, CA",
		"La Habra, CA",
		"Lake Charles, LA",
		"Lake Elsinore, CA",
		"Lake Forest, CA",
		"Lake Havasu City, AZ",
		"Lakeland, FL",
		"Lake Magdalene, FL",
		"Lakeville, MN",
		"Lakewood, CO",
		"Lakewood, CA",
		"Lakewood, WA",
		"Lakewood, OH",
		"Lakewood, NJ",
		"La Mesa, CA",
		"La Mirada, CA",
		"Lancaster, CA",
		"Lancaster, PA",
		"Land O' Lakes, FL",
		"Land O'Lakes, FL",
		"Lansing, MI",
		"La Puente, CA",
		"La Quinta, CA",
		"Laredo, TX",
		"Largo, FL",
		"Las Cruces, NM",
		"Las Vegas, NV",
		"Lauderhill, FL",
		"Lawrence, KS",
		"Lawrence, MA",
		"Lawrence, IN",
		"Lawton, OK",
		"Layton, UT",
		"League City, TX",
		"Leesburg, VA",
		"Lee's Summit, MO",
		"Lehi, UT",
		"Lehigh Acres, FL",
		"Lenexa, KS",
		"Leominster, MA",
		"Levittown, NY",
		"Levittown, PA",
		"Lewisville, TX",
		"Lexington, KY",
		"Lincoln, NE",
		"Lincoln, CA",
		"Little Rock, AR",
		"Littleton, CO",
		"Livermore, CA",
		"Livonia, MI",
		"Lodi, CA",
		"Logan, UT",
		"Lombard, IL",
		"Lompoc, CA",
		"Long Beach, CA",
		"Longmont, CO",
		"Longview, TX",
		"Lorain, OH",
		"Los Angeles, CA",
		"Louisville, KY",
		"Loveland, CO",
		"Lowell, MA",
		"Lower Merion, PA",
		"Lubbock, TX",
		"Lynchburg, VA",
		"Lynn, MA",
		"Lynwood, CA",
		"MacAllen, TX",
		"MacKinney, TX",
		"Macon, GA",
		"Madera, CA",
		"Madison, WI",
		"Malden, MA",
		"Manchester, NH",
		"Manhattan, KS",
		"Mansfield, TX",
		"Mansfield, OH",
		"Manteca, CA",
		"Maple Grove, MN",
		"Margate, FL",
		"Maricopa, AZ",
		"Marietta, GA",
		"Medford, OR",
		"Medford, MA",
		"Melbourne, FL",
		"Memphis, TN",
		"Mentor, OH",
		"Merced, CA",
		"Meriden, CT",
		"Meridian, ID",
		"Mesa, AZ",
		"Mesquite, TX",
		"Metairie, LA",
		"Methuen, MA",
		"Miami, FL",
		"Miami Beach, FL",
		"Miami Gardens, FL",
		"Middletown, OH",
		"Middletown, CT",
		"Midland, TX",
		"Midland, MI",
		"Midwest City, OK",
		"Milford, CT",
		"Milpitas, CA",
		"Milwaukee, WI",
		"Minneapolis, MN",
		"Minnetonka, MN",
		"Miramar, FL",
		"Mishawaka, IN",
		"Mission, TX",
		"Mission Viejo, CA",
		"Missoula, Montana",
		"MO City, TX",
		"Mobile, AL",
		"Modesto, CA",
		"Moline, IL",
		"Monroe, LA",
		"Montebello, CA",
		"Monterey Park, CA",
		"Montgomery, AL",
		"Montgomery Village, MD",
		"Moore, OK",
		"Moreno Valley, CA",
		"Mountain View, CA",
		"Mount Pleasant, SC",
		"Mount Prospect, IL",
		"Mount Vernon, NY",
		"Muncie, IN",
		"Murfreesboro, TN",
		"Murray, UT",
		"Murrieta, CA",
		"Nampa, ID",
		"Napa, CA",
		"Naperville, IL",
		"Nashua, NH",
		"Nashville, TN",
		"National City, CA",
		"Newark, NJ",
		"Newark, OH",
		"Newark, CA",
		"New Bedford, MA",
		"New Braunfels, TX",
		"New Britain, CT",
		"New Brunswick, NJ",
		"New Haven, CT",
		"New Orleans, LA",
		"Newport Beach, CA",
		"Newport News, VA",
		"New Rochelle, NY",
		"Newton, MA",
		"NY, NY",
		"Niagara Falls, NY",
		"Noblesville, IN",
		"Norfolk, VA",
		"Normal, IL",
		"Norman, OK",
		"North Atlanta, GA",
		"North Attleborough, MA",
		"North Bergen, NJ",
		"North Bethesda, MD",
		"North Charleston, SC",
		"North Fort Myers, FL",
		"North Highlands, CA",
		"North Las Vegas, NV",
		"North Lauderdale, FL",
		"North Little Rock, AR",
		"North Miami, FL",
		"North Port, FL",
		"North Richland Hills, TX",
		"Norwalk, CA",
		"Norwalk, CT",
		"Novato, CA",
		"Novi, MI",
		"Oakland, CA",
		"Oakland Park, FL",
		"Oak Lawn, IL",
		"Oak Park, IL",
		"Ocala, FL",
		"Oceanside, CA",
		"Odessa, TX",
		"O'Fallon, MO",
		"Ogden, UT",
		"Oklahoma City, OK",
		"Olathe, KS",
		"Olney, MD",
		"Olympia, WA",
		"Omaha, NE",
		"Ontario, CA",
		"Orange, CA",
		"Orem, UT",
		"Orlando, FL",
		"Orland Park, IL",
		"Oro Valley, AZ",
		"Oshkosh, WI",
		"Overland Park, KS",
		"Owensboro, KY",
		"Oxnard, CA",
		"Palatine, IL",
		"Palm Bay, FL",
		"Palm Beach Gardens, FL",
		"Palm Coast, FL",
		"Palmdale, CA",
		"Palm Desert, CA",
		"Palm Harbor, FL",
		"Palm Springs, CA",
		"Palo Alto, CA",
		"Paradise, NV",
		"Paramount, CA",
		"Parker, CO",
		"Parkway-South Sacramento, CA",
		"Parma, OH",
		"Parsippany-Troy Hills Township, NJ",
		"Pasadena, TX",
		"Pasadena, CA",
		"Pasco, WA",
		"Passaic, NJ",
		"Paterson, NJ",
		"Pawtucket, RI",
		"Peabody, MA",
		"Pearland, TX",
		"Pembroke Pines, FL",
		"Penn Hills, PA",
		"Pensacola, FL",
		"Peoria, AZ",
		"Peoria, IL",
		"Perris, CA",
		"Perth Amboy, NJ",
		"Petaluma, CA",
		"Pflugerville, TX",
		"Pharr, TX",
		"Philadelphia, PA",
		"Phoenix, AZ",
		"Pico Rivera, CA",
		"Pine Bluff, AR",
		"Pine Hills, FL",
		"Pinellas Park, FL",
		"Pittsburg, CA",
		"Pittsburgh, PA",
		"Pittsfield, MA",
		"Placentia, CA",
		"Plainfield, NJ",
		"Plano, TX",
		"Plantation, FL",
		"Pleasanton, CA",
		"Plymouth, MN",
		"Plymouth, MA",
		"Pocatello, ID",
		"Pomona, CA",
		"Pompano Beach, FL",
		"Pontiac, MI",
		"Portage, MI",
		"Port Arthur, TX",
		"Port Charlotte, FL",
		"Porterville, CA",
		"Portland, OR",
		"Portland, Maine",
		"Port Orange, FL",
		"Port Saint Lucie, FL",
		"Portsmouth, VA",
		"Potomac, MD",
		"Poway, CA",
		"Prescott, AZ",
		"Prescott Valley, AZ",
		"Providence, RI",
		"Provo, UT",
		"Pueblo, CO",
		"Quincy, MA",
		"Racine, WI",
		"Raleigh, NC",
		"Rancho Cordova, CA",
		"Rancho Cucamonga, CA",
		"Rancho Palos Verdes, CA",
		"Rancho Santa Margarita, CA",
		"Rapid City, SD",
		"Reading, PA",
		"Redan, GA",
		"Redding, CA",
		"Redford, MI",
		"Redlands, CA",
		"Redmond, WA",
		"Redondo Beach, CA",
		"Redwood City, CA",
		"Reno, NV",
		"Renton, WA",
		"Reston, VA",
		"Revere, MA",
		"Rialto, CA",
		"Richardson, TX",
		"Richland, WA",
		"Richmond, VA",
		"Richmond, CA",
		"Rio Rancho, NM",
		"Riverside, CA",
		"Riverton, UT",
		"Roanoke, VA",
		"Rochester, NY",
		"Rochester, MN",
		"Rochester Hills, MI",
		"Rockford, IL",
		"Rock Hill, SC",
		"Rocklin, CA",
		"Rockville, MD",
		"Rocky Mount, NC",
		"Rogers, AR",
		"Rohnert Park, CA",
		"Rosemead, CA",
		"Roseville, CA",
		"Roseville, MI",
		"Roswell, GA",
		"Roswell, NM",
		"Round Rock, TX",
		"Rowland Heights, CA",
		"Rowlett, TX",
		"Royal Oak, MI",
		"Sacramento, CA",
		"Saginaw, MI",
		"Saint Charles, MO",
		"Saint Clair Shores, MI",
		"Saint Cloud, MN",
		"Saint George, UT",
		"Saint Joseph, MO",
		"Saint Louis, MO",
		"Saint Louis Park, MN",
		"Saint Paul, MN",
		"Saint Peters, MO",
		"Saint Petersburg, FL",
		"Salem, OR",
		"Salem, MA",
		"Salina, KS",
		"Salinas, CA",
		"Salt Lake City, UT",
		"Sammamish, WA",
		"San Angelo, TX",
		"San Antonio, TX",
		"San Bernardino, CA",
		"San Bruno, CA",
		"San Buenaventura, CA",
		"San Clemente, CA",
		"San Diego, CA",
		"Sandy, UT",
		"Sandy Springs, GA",
		"Sanford, FL",
		"San Francisco, CA",
		"San Gabriel, CA",
		"San Jose, CA",
		"San Leandro, CA",
		"San Luis Obispo, CA",
		"San Marcos, CA",
		"San Marcos, TX",
		"San Mateo, CA",
		"San Rafael, CA",
		"San Ramon, CA",
		"Santa Ana, CA",
		"Santa Barbara, CA",
		"Santa Clara, CA",
		"Santa Clarita, CA",
		"Santa Cruz, CA",
		"Santa Fe, NM",
		"Santa Maria, CA",
		"Santa Monica, CA",
		"Santa Rosa, CA",
		"Santee, CA",
		"Sarasota, FL",
		"Savannah, GA",
		"Sayreville, NJ",
		"Schaumburg, IL",
		"Schenectady, NY",
		"Scottsdale, AZ",
		"Scranton, PA",
		"Seattle, WA",
		"Seattle Hill-Silver Firs, WA",
		"Severn, MD",
		"Shawnee, KS",
		"Sheboygan, WI",
		"Shoreline, WA",
		"Shreveport, LA",
		"Sierra Vista, AZ",
		"Silver Spring, MD",
		"Simi Valley, CA",
		"Sioux City, IA",
		"Sioux Falls, SD",
		"Skokie, IL",
		"Smyrna, GA",
		"Smyrna, TN",
		"Somerville, MA",
		"Southaven, MI",
		"South Bend, IN",
		"Southfield, MI",
		"South Gate, CA",
		"Southglenn, CO",
		"South Hill, WA",
		"South Jordan, UT",
		"South San Francisco, CA",
		"South Whittier, CA",
		"Sparks, NV",
		"Spartanburg, SC",
		"Spokane, WA",
		"Spokane Valley, WA",
		"Springdale, AR",
		"Springfield, MO",
		"Springfield, MA",
		"Springfield, IL",
		"Springfield, OH",
		"Springfield, OR",
		"Spring Hill, FL",
		"Spring Valley, NV",
		"Stamford, CT",
		"Sterling, VA",
		"Sterling Heights, MI",
		"Stillwater, OK",
		"Stockton, CA",
		"Stratford, CT",
		"Strongsville, OH",
		"Suffolk, VA",
		"Sugar Land, TX",
		"Summerville, SC",
		"Sun City, AZ",
		"Sun City West, AZ",
		"Sunnyvale, CA",
		"Sunrise, FL",
		"Sunrise Manor, NV",
		"Surprise, AZ",
		"Syracuse, NY",
		"Tacoma, WA",
		"Tallahassee, FL",
		"Tamarac, FL",
		"Tamiami, FL",
		"Tampa, FL",
		"Taunton, MA",
		"Taylor, MI",
		"Taylorsville, UT",
		"Temecula, CA",
		"Tempe, AZ",
		"Temple, TX",
		"Terre Haute, IN",
		"TX City, TX",
		"The Colony, TX",
		"The Hammocks, FL",
		"The Woodlands, TX",
		"Thornton, CO",
		"Thousand Oaks, CA",
		"Tigard, OR",
		"Tinley Park, IL",
		"Titusville, FL",
		"Toledo, OH",
		"Toms River, NJ",
		"Tonawanda CDP, NY",
		"Topeka, KS",
		"Torrance, CA",
		"Town'n'Country, FL",
		"Towson, MD",
		"Tracy, CA",
		"Trenton, NJ",
		"Troy, MI",
		"Troy, NY",
		"Tuckahoe, VA",
		"Tucson, AZ",
		"Tulare, CA",
		"Tulsa, OK",
		"Turlock, CA",
		"Tuscaloosa, AL",
		"Tustin, CA",
		"Twin Falls, ID",
		"Tyler, TX",
		"Union, NJ",
		"Union City, CA",
		"Union City, NJ",
		"Upland, CA",
		"Utica, NY",
		"Vacaville, CA",
		"Valdosta, GA",
		"Vallejo, CA",
		"Vancouver, WA",
		"Victoria, TX",
		"Victorville, CA",
		"Vineland, NJ",
		"Virginia Beach, VA",
		"Visalia, CA",
		"Vista, CA",
		"Waco, TX",
		"Walnut Creek, CA",
		"Waltham, MA",
		"Warner Robins, GA",
		"Warren, MI",
		"Warren, OH",
		"Warwick, RI",
		"Washington, DC",
		"Waterbury, CT",
		"Waterford, MI",
		"Waterloo, IA",
		"Watsonville, CA",
		"Waukegan, IL",
		"Waukesha, WI",
		"Wauwatosa, WI",
		"Wayne, NJ",
		"Wellington, FL",
		"West Allis, WI",
		"West Babylon, NY",
		"West Bloomfield Township, MI",
		"West Covina, CA",
		"West Des Moines, IA",
		"Westfield, MA",
		"West Haven, CT",
		"West Hartford, CT",
		"West Jordan, UT",
		"Westland, MI",
		"Westminster, CO",
		"Westminster, CA",
		"West NY, NJ",
		"Weston, FL",
		"West Orange, NJ",
		"West Palm Beach, FL",
		"West Sacramento, CA",
		"West Seneca, NY",
		"West Valley City, UT",
		"Weymouth, MA",
		"Wheaton, IL",
		"Wheaton-Glenmont, MD",
		"White Plains, NY",
		"Whittier, CA",
		"Wichita, KS",
		"Wichita Falls, TX",
		"Wilmington, NC",
		"Wilmington, DE",
		"Wilson, NC",
		"Winston-Salem, NC",
		"Woodbury, MN",
		"Woodland, CA",
		"Woonsocket, RI",
		"Worcester, MA",
		"Wylie, TX",
		"Wyoming, MI",
		"Yakima, WA",
		"Yonkers, NY",
		"Yorba Linda, CA",
		"Youngstown, OH",
		"Yuba City, CA",
		"Yucaipa, CA",
		"Yuma, AZ"
	];
	
		$( "#geo" ).autocomplete({
			source: cities,
			minLength: 2,
			appendTo: "#location-finder-input",
			select: function( event, ui ) {
				$('#geo').val(ui.item.label);				
				$('#location-finder-done').click();				
				
			},
			open: function() {				
				$( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
				$('.ui-tooltip').hide();
			},
			close: function() {
				$( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
			}
		}); 	


	
	
	/*
	$('#country-finder').live('keyup.autocomplete', function(){
		
		$('#country-finder-done').show();

		$(this).autocomplete({
			source: countries,
			minLength: 0,
			appendTo: "#country-finder-input",
			select: function( event, ui ) {
					
				$.params.ip = '';
				$.params.geo = '';
				$.params.zip = '';
				$.params.country = ui.item.label;		
				$('#location-finder-country').html(ui.item.label);
				$('#geo').val('');
				$('#location-finder-change-country').click();
				//$('#location-finder-done').click();
				
			},
			
			open: function() {				
				$( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
			},
			close: function() {
				$( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
			}
		}).result(function(event, item) {
			$(this).prev().val(item.Key);
		});
	
	}); 
	*/
	
	
	
	

	
	
	
});	